### ISSUE TITLE
[Question] on use of .UseContentRoot() in cli-samples

### ISSUE THREAD

**Issue by GuardRex** [aspnet/cli-samples#34]
`.UseContentRoot(Directory.GetCurrentDirectory())` provides the path for `ContentRootPath`, but `ContentRootPath` receives the value of `Directory.GetCurrentDirectory()` automatically, so I was just curious why it appears on the `WebHostBuilder` at all? It is optional to call this extension with that value assignment, isn't it?

**Comment by davidfowl** [comment]
In web applications the static files and views won't be copied to the output folder on build. It is being copied right now but that's a bug because it too slow and changing static files shouldn't require a build step to see changes.  Because of this we want the content root to work both when developing and when the app is published. This means that we need a way to point the content root to the project folder when developing and a way to point it to the output folder on publish. We set the content root to the current directory so that `dotnet run` works during dev and loads views from the right place on publish. When running in IIS, the `web.config` file being in the wwwroot folder, throws the working directory off so we need to override that setting via publish IIS.

**Comment by GuardRex** [comment]
> When running in IIS, the web.config file being in the wwwroot folder, throws the working directory off so we need to override that setting via publish IIS.

Ok ... I think I get it. I'm still a hair confused by your last line, because `ContentRootPath` is set correctly when run on the IIS server (and views are found and served properly) when the extension method is **not** present, so there is no problem when published output is moved to the server.

On the dev side, I get it. @moozzyk has touched base on this issue with me before on `ApplicationBasePath`, and that's exactly what he told me when we chatted about this a few months back. I just didn't recognize it was the same situation playing out.

**Comment by rjpaulsen** [comment]
It seems that if Project1 uses the same views as Project2, can I set UseContentRoot() in Project2 to point to Project1.

Is that an intended use of UseContentRoot()?
